config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :pokemons

  root 'welcome#index'

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base

  validates :pokename, presence: true,
                   length: { minimum: 2 }
  validates :poketype1, presence: true,
                    length: { minimum: 2 }
  validates :poketype2, presence: true,
                    length: { minimum: 2 }
  validates :pokemove1, presence: true,
                    length: { minimum: 2 }
  validates :pokemove2, presence: true,
                    length: { minimum: 2 }
  validates :pokemove3, presence: true,
                    length: { minimum: 2 }
  validates :pokemove4, presence: true,
                    length: { minimum: 2 }
  validates :pokeweakness1, presence: true,
                    length: { minimum: 2 }
  validates :pokeweakness2, presence: true,
                    length: { minimum: 2 }
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def new
    @pokemon = Pokemon.new
  end

  def edit
    @pokemon = Pokemon.find(params[:id])
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)

    if @pokemon.save
      redirect_to @pokemon
    else
      render 'new'
    end
  end

  def update
    @pokemon = Pokemon.find(params[:id])

    if @pokemon.update(pokemon_params)
      redirect_to @pokemon
    else
      render 'pokemon'
    end
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy

    redirect_to pokemons_path
  end

  private
    def pokemon_params
      params.require(:pokemon).permit(:pokename, :poketype1, :poketype2, :pokemove1, :pokemove2, :pokemove3, :pokemove4, :pokeweakness1, :pokeweakness2, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pkdex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pokemons/_form.html.erb
<%= form_for @pokemon, :html => {:multipart => true} do |f| %>


      <%= link_to 'Pokemon List', pokemons_path, class:"button_link left"%>
      <%= f.submit :Save,class:"button_link right" %>
      <div class="pokemon_form_main">
        <p>
          <%= f.file_field :image %>
        </p>

        <p>Pokemon</p>
        <center><%= f.text_field :pokename %></center>

        <p>Types</p>
          <%= f.text_field :poketype1 %>
          <%= f.text_field :poketype2 %>

        <p>Moves</p>
          <%= f.text_field :pokemove1 %>
          <%= f.text_field :pokemove2 %>
          <%= f.text_field :pokemove3 %>
          <%= f.text_field :pokemove4 %>

        <p>Weakness</p>
          <%= f.text_field :pokeweakness1 %>
          <%= f.text_field :pokeweakness2 %>
      </div>
  <% end %>

app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render 'form' %>

app/views/pokemons/index.html.erb
<div class="pokedex-main">

  <div class="pokedex_title">
    <h1>Pokedex</h1>
  </div>
<head>
  <title>Pokedex</title>




</head>


<body>
  <%= link_to 'New Pokemon', new_pokemon_path %>
    <table class="pokedex_table_main">
      <tr>
        <th colspan="1" class="pokedex_table_title">Image</th>
        <th class="pokedex_table_title">Pokemon</th>
        <th class="pokedex_table_title">Type 1</th>
        <th class="pokedex_table_title">Type 2</th>
        <th colspan="3" class="pokedex_table_title">Actions</th>
      </tr>

      <% @pokemons.each do |pokemon| %>
        <tr class="pokedex_table_element">
          <td><%= image_tag pokemon.image_url(:thumb).to_s %></td>
          <td><%= pokemon.pokename %></td>
          <td><%= pokemon.poketype1 %></td>
          <td><%= pokemon.poketype2 %></td>
          <td><%= link_to 'Show', pokemon_path(pokemon) %></td>
          <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
          <td><%= link_to 'Destroy', pokemon_path(pokemon),
                    method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>



</body>
</div>

app/views/pokemons/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p>
  <%= image_tag @pokemon.image_url(:thumb).to_s %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.pokename %>
</p>

<p>
  <strong>Type 1:</strong>
  <%= @pokemon.poketype1 %>
</p>

<p>
  <strong>Type 2:</strong>
  <%= @pokemon.poketype2 %>
</p>

<p>
  <strong>Moves 1:</strong>
  <%= @pokemon.pokemove1 %>
</p>

<p>
  <strong>Moves 2:</strong>
  <%= @pokemon.pokemove2 %>
</p>

<p>
  <strong>Move 3:</strong>
  <%= @pokemon.pokemove3 %>
</p>

<p>
  <strong>Move 4:</strong>
  <%= @pokemon.pokemove4 %>
</p>

<p>
  <strong>Weakness 1:</strong>
  <%= @pokemon.pokeweakness1 %>
</p>

<p>
  <strong>Weakness 2:</strong>
  <%= @pokemon.pokeweakness2 %>
</p>
<%= link_to 'Back', pokemons_path %>

app/views/welcome/index.html.erb
Hi there!

<%= link_to 'Pokemon Database', pokemons_path %>